In [1]:
import pandas as pd
import sqlite3

In [2]:
con=sqlite3.connect('inventory.db')

In [3]:
tables=pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",con)
tables

                   name
0  Vendor_Sales_Summary
1     vendor_sales_summ
2       begin_inventory
3         end_inventory
4             purchases
5       purchase_prices
6                 sales
7        vendor_invoice

In [4]:
for i in tables['name']:
    print(f'{i}', '!'*5)
    print("Count of Records:", pd.read_sql(f"select count() as count from {i}",con)['count'].values[0])
    display(pd.read_sql(f"select * from {i} limit 5",con))

Vendor_Sales_Summary !!!!!
Count of Records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,Profit,ProfitMargin,StockTurnover,S2PRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

vendor_sales_summ !!!!!
Count of Records: 10692

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,Profit,ProfitMargin,StockTurnover,S2PRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897

begin_inventory !!!!!
Count of Records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

end_inventory !!!!!
Count of Records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

purchases !!!!!
Count of Records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

purchase_prices !!!!!
Count of Records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

sales !!!!!
Count of Records: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

vendor_invoice !!!!!
Count of Records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [5]:
purchases=pd.read_sql_query("select * from purchases where VendorNumber=388",con)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1
1,42_BLACK HOLLOW_2034,42,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8249,2023-12-30,2024-01-06,2024-01-11,2024-02-18,21.32,30,639.60,1
2,79_BALLYMENA_2034,79,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8249,2023-12-30,2024-01-09,2024-01-11,2024-02-18,21.32,35,746.20,1
3,32_MOUNTMEND_2034,32,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8249,2023-12-30,2024-01-05,2024-01-11,2024-02-18,21.32,6,127.92,1
4,50_MOUNTMEND_2034,50,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8249,2023-12-30,2024-01-06,2024-01-11,2024-02-18,21.32,6,127.92,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,70_KELD_2034,70,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,13624,2024-12-22,2024-12-27,2025-01-06,2025-02-07,21.32,6,127.92,1
262,1_HARDERSFIELD_2034,1,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,13624,2024-12-22,2024-12-31,2025-01-06,2025-02-07,21.32,6,127.92,1
263,32_MOUNTMEND_2034,32,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,13624,2024-12-22,2024-12-27,2025-01-06,2025-02-07,21.32,6,127.92,1
264,59_CLAETHORPES_2034,59,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,13624,2024-12-22,2024-12-28,2025-01-06,2025-02-07,21.32,6,127.92,1
265,51_ABERDEEN_2034,51,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,13624,2024-12-22,2024-12-30,2025-01-06,2025-02-07,21.32,6,127.92,1

In [6]:
purchase_prices=pd.read_sql_query("select * from purchase_prices where VendorNumber=388",con)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,2034,Glendalough Double Barrel,32.99,750mL,750,1,21.32,388,ATLANTIC IMPORTING COMPANY
1,2119,Glendalough 13 Yr Sngle Malt,89.99,750mL,750,1,66.40,388,ATLANTIC IMPORTING COMPANY
2,7241,Glendalough Poitin Shry Cask,34.99,750mL,750,2,20.68,388,ATLANTIC IMPORTING COMPANY

In [7]:
vendor_invoice=pd.read_sql_query("select * from vendor_invoice where VendorNumber=388",con)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
1,388,ATLANTIC IMPORTING COMPANY,2024-01-11,8249,2023-12-30,2024-02-18,95,2025.40,10.73,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-25,8323,2024-01-04,2024-02-23,64,1364.48,7.10,None
3,388,ATLANTIC IMPORTING COMPANY,2024-01-31,8456,2024-01-13,2024-02-28,18,379.92,1.98,None
4,388,ATLANTIC IMPORTING COMPANY,2024-02-03,8497,2024-01-17,2024-03-08,83,2028.52,9.53,None
5,388,ATLANTIC IMPORTING COMPANY,2024-02-08,8675,2024-01-28,2024-03-13,82,1748.24,9.27,None
6,388,ATLANTIC IMPORTING COMPANY,2024-02-19,8704,2024-01-31,2024-03-20,24,511.68,2.40,None
7,388,ATLANTIC IMPORTING COMPANY,2024-02-25,8893,2024-02-12,2024-03-29,12,255.84,1.18,None
8,388,ATLANTIC IMPORTING COMPANY,2024-02-29,8962,2024-02-17,2024-04-08,29,618.28,3.34,None
9,388,ATLANTIC IMPORTING COMPANY,2024-03-08,9095,2024-02-26,2024-04-20,54,1151.28,6.22,None
10,388,ATLANTIC IMPORTING COMPANY,2024-03-22,9112,2024-02-28,2024-04-23,36,812.60,4.31,None
11,388,ATLANTIC IMPORTING COMPANY,2024-03-26,9228,2024-03-07,2024-04-23,84,2422.00,11.38,None
12,388,ATLANTIC IMPORTING COMPANY,2024-03-30,9357,2024-03-16,2024-05-13,42,895.44,4.84,None
13,388,ATLANTIC IMPORTING COMPANY,2024-04-06,9504,2024-03-25,2024-05-17,4,85.28,0.41,None
14,388,ATLANTIC IMPORTING COMPANY,2024-04-15,9519,2024-03-27,2024-05-15,17,362.44,1.85,None
15,388,ATLANTIC IMPORTING COMPANY,2024-04-24,9640,2024-04-04,2024-05-22,18,383.76,2.03,None
16,388,ATLANTIC IMPORTING COMPANY,2024-04-29,9762,2024-04-13,2024-06-06,24,511.68,2.61,None
17,388,ATLANTIC IMPORTING COMPANY,2024-05-09,9818,2024-04-17,2024-06-04,29,618.28,2.97,None
18,388,ATLANTIC IMPORTING COMPANY,2024-05-11,9969,2024-04-27,2024-06-14,17,362.44,1.96,None
19,388,ATLANTIC IMPORTING COMPANY,2024-05-24,10033,2024-05-02,2024-06-16,18,383.76,1.88,None
20,388,ATLANTIC IMPORTING COMPANY,2024-05-31,10116,2024-05-08,2024-07-05,30,906.24,4.17,None
21,388,ATLANTIC IMPORTING COMPANY,2024-06-07,10273,2024-05-18,2024-07-09,11,234.52,1.22,None
22,388,ATLANTIC IMPORTING COMPANY,2024-06-13,10347,2024-05-23,2024-07-21,18,383.76,2.00,None
23,388,ATLANTIC IMPORTING COMPANY,2024-06-15,10478,2024-06-01,2024-07-30,30,639.60,3.45,None
24,388,ATLANTIC IMPORTING COMPANY,2024-06-21,10579,2024-06-08,2024-07-30,18,383.76,1.84,None
25,388,ATLANTIC IMPORTING COMPANY,2024-07-04,10645,2024-06-13,2024-08-05,11,234.52,1.29,None
26,388,ATLANTIC IMPORTING COMPANY,2024-07-11,10764,2024-06-21,2024-08-09,12,255.84,1.30,None
27,388,ATLANTIC IMPORTING COMPANY,2024-07-11,10970,2024-06-29,2024-08-17,30,639.60,3.33,None
28,388,ATLANTIC IMPORTING COMPANY,2024-07-25,11024,2024-07-03,2024-08-20,183,3901.56,18.34,None
29,388,ATLANTIC IMPORTING COMPANY,2024-07-25,11171,2024-07-13,2024-09-05,19,405.08,1.86,None
30,388,ATLANTIC IMPORTING COMPANY,2024-08-07,11261,2024-07-19,2024-09-15,22,469.04,2.49,None
31,388,ATLANTIC IMPORTING COMPANY,2024-08-08,11411,2024-07-29,2024-09-18,23,490.36,2.30,None
32,388,ATLANTIC IMPORTING COMPANY,2024-08-15,11427,2024-07-31,2024-09-20,18,383.76,2.11,None
33,388,ATLANTIC IMPORTING COMPANY,2024-08-23,11567,2024-08-09,2024-10-06,36,767.52,3.53,None
34,388,ATLANTIC IMPORTING COMPANY,2024-08-31,11667,2024-08-16,2024-10-08,11,234.52,1.29,None
35,388,ATLANTIC IMPORTING COMPANY,2024-09-09,11791,2024-08-24,2024-10-20,41,874.12,4.55,None
36,388,ATLANTIC IMPORTING COMPANY,2024-09-15,11902,2024-09-01,2024-10-16,30,639.60,3.52,None
37,388,ATLANTIC IMPORTING COMPANY,2024-09-26,11971,2024-09-06,2024-11-03,18,383.76,2.07,None
38,388,ATLANTIC IMPORTING COMPANY,2024-10-04,12107,2024-09-15,2024-11-09,18,383.76,2.03,None
39,388,ATLANTIC IMPORTING COMPANY,2024-10-09,12180,2024-09-20,2024-11-10,12,526.32,2.74,None
40,388,ATLANTIC IMPORTING COMPANY,2024-10-13,12361,2024-09-28,2024-11-18,23,490.36,2.50,None
41,388,ATLANTIC IMPORTING COMPANY,2024-10-17,12467,2024-10-05,2024-12-02,34,724.88,3.70,None
42,388,ATLANTIC IMPORTING COMPANY,2024-11-01,12516,2024-10-09,2024-12-08,24,511.68,2.66,None
43,388,ATLANTIC IMPORTING COMPANY,2024-11-07,12686,2024-10-20,2024-12-14,71,1513.72,7.27,None
44,388,ATLANTIC IMPORTING COMPANY,2024-11-15,12792,2024-10-27,2024-12-16,48,1023.36,5.32,None
45,388,ATLANTIC IMPORTING COMPANY,2024-11-18,12898,2024-11-03,2024-12-17,50,1066.00,5.65,None
46,388,ATLANTIC IMPORTING COMPANY,2024-11-25,12991,2024-11-10,2024-12-31,6,398.40,2.11,None
47,388,ATLANTIC IMPORTING COMPANY,2024-11-28,13076,2024-11-15,2025-01-08,71,1513.72,6.81,None
48,388,ATLANTIC IMPORTING COMPANY,2024-12-10,13200,2024-11-24,2025-01-16,16,340.48,1.74,None
49,388,ATLANTIC IMPORTING COMPANY,2024-12-17,13237,2024-11-27,2025-01-22,36,767.52,3.99,None
50,388,ATLANTIC IMPORTING COMPANY,2024-12-22,13369,2024-12-06,2025-01-22,39,831.48,4.49,None
51,388,ATLANTIC IMPORTING COMPANY,2024-12-26,13535,2024-12-16,2025-01-27,30,639.60,3.26,None
52,388,ATLANTIC IMPORTING COMPANY,2025-01-02,13592,2024-12-20,2025-02-02,53,1129.96,6.21,None

In [8]:
sales=pd.read_sql_query("select * from sales where VendorNo=388",con)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_2034,1,2034,Glendalough Double Barrel,750mL,1,28.99,28.99,2024-01-12,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
1,1_HARDERSFIELD_2034,1,2034,Glendalough Double Barrel,750mL,1,28.99,28.99,2024-01-13,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
2,1_HARDERSFIELD_2034,1,2034,Glendalough Double Barrel,750mL,1,28.99,28.99,2024-01-20,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
3,1_HARDERSFIELD_2034,1,2034,Glendalough Double Barrel,750mL,1,28.99,28.99,2024-01-22,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
4,10_HORNSEY_2034,10,2034,Glendalough Double Barrel,750mL,1,28.99,28.99,2024-01-20,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,7_STANMORE_2034,7,2034,Glendalough Double Barrel,750mL,1,27.99,27.99,2024-12-21,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
1476,81_PEMBROKE_2034,81,2034,Glendalough Double Barrel,750mL,2,55.98,27.99,2024-12-19,750.0,1,1.57,388,ATLANTIC IMPORTING COMPANY
1477,81_PEMBROKE_2034,81,2034,Glendalough Double Barrel,750mL,1,27.99,27.99,2024-12-30,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
1478,9_BLACKPOOL_2034,9,2034,Glendalough Double Barrel,750mL,1,27.99,27.99,2024-12-01,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY
1479,9_BLACKPOOL_2034,9,2034,Glendalough Double Barrel,750mL,1,27.99,27.99,2024-12-17,750.0,1,0.79,388,ATLANTIC IMPORTING COMPANY

In [9]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
2034  21.32              1777  37885.64
2119  66.40                39   2589.60
7241  20.68                31    641.08

In [10]:
sales.groupby('Brand')[['SalesDollars','SalesQuantity','SalesPrice']].sum()

       SalesDollars  SalesQuantity  SalesPrice
Brand
2034       45645.13           1587    37387.00
2119        9838.85            115     6924.19
7241        3788.77            123     2989.01

In [11]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='object')

In [12]:
freight_summ=pd.read_sql_query("""select VendorNumber, SUM(Freight) as FreightCost From vendor_invoice GROUP BY VendorNumber""",con)
freight_summ

     VendorNumber  FreightCost
0               2        27.08
1              54         0.48
2              60       367.52
3             105        62.39
4             200         6.19
..            ...          ...
121         98450       856.02
122         99166       130.09
123        172662       178.34
124        173357       202.50
125        201359         0.09

[126 rows x 2 columns]

In [13]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='object')

In [14]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='object')

In [15]:
pd.read_sql_query("""SELECT p.VendorNumber,p.VendorName,p.Brand,p.PurchasePrice,pp.Volume,pp.Price as ActualPrice,
SUM(p.Quantity) as TotalPurchaseQuantity,SUM(p.Dollars) as TotalPurchaseDollars FROM purchases p JOIN purchase_prices pp
ON p.Brand=pp.Brand Where p.PurchasePrice>0 GROUP BY p.VendorNumber, p.VendorName, p.Brand ORDER BY TotalPurchaseDollars""",con)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080,3811251.60

In [16]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='object')

In [17]:
pd.read_sql_query("""SELECT VendorNo,Brand,SUM(SalesDollars) as TotalSalesDollars,SUM(SalesPrice) as TotalSalesPrice,
SUM(SalesQuantity) as TotalSalesQuantity,SUM(ExciseTax) as TotalExciseTax FROM sales GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars""",con)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2,0.10
1,9206,2773,0.99,0.99,1,0.05
2,3252,3933,1.98,0.99,2,0.10
3,3924,9123,1.98,0.99,2,0.10
4,10050,3623,1.98,1.98,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4223107.62,545778.28,135838,249587.83
11268,3960,4261,4475972.88,420050.01,200412,368242.80
11269,17035,8068,4538120.60,461140.15,187140,343854.07
11270,4425,3405,4819073.49,561512.37,160247,294438.66
11271,1128,1233,5101919.51,672819.31,142049,260999.20

In [18]:
vendor_sales_summ = pd.read_sql_query("""
WITH FreightSummary AS (
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),
PurchaseSummary AS (
    SELECT
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Dollars) AS TotalPurchaseDollars
    FROM purchases AS p
    JOIN purchase_prices AS pp ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price,
        pp.Volume
),
SalesSummary AS (
    SELECT
        s.VendorNo,
        s.Brand,
        SUM(s.SalesQuantity) AS TotalSalesQuantity,
        SUM(s.SalesDollars) AS TotalSalesDollars,
        SUM(s.SalesPrice) AS TotalSalesPrice,
        SUM(s.ExciseTax) AS TotalExciseTax
    FROM sales AS s
    GROUP BY s.VendorNo, s.Brand
)
SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary AS ps
LEFT JOIN SalesSummary AS ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary AS fs
    ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""", con)

In [19]:
vendor_sales_summ

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,5.0,15.95,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,134.0,65.66,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,2.0,1.98,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,72.0,143.28,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,86.0,85.14,33.66,4.46,38994.78

In [20]:
vendor_sales_summ.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
Description               object
PurchasePrice            float64
ActualPrice              float64
Volume                    object
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [21]:
vendor_sales_summ.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       178
TotalSalesDollars        178
TotalSalesPrice          178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [22]:
vendor_sales_summ['Volume']=vendor_sales_summ['Volume'].astype('float64')

In [23]:
vendor_sales_summ['VendorName']=vendor_sales_summ['VendorName'].str.strip()

In [24]:
vendor_sales_summ.fillna(0,inplace=True)

In [25]:
vendor_sales_summ['Profit']=vendor_sales_summ['TotalSalesDollars']-vendor_sales_summ['TotalPurchaseDollars']

In [26]:
vendor_sales_summ['ProfitMargin']=(vendor_sales_summ['Profit']/vendor_sales_summ['TotalSalesDollars'])*100

In [27]:
vendor_sales_summ['StockTurnover']=(vendor_sales_summ['TotalSalesQuantity']/vendor_sales_summ['TotalPurchaseQuantity'])

In [28]:
vendor_sales_summ['S2PRatio']=(vendor_sales_summ['TotalSalesDollars']/vendor_sales_summ['TotalPurchaseDollars'])

In [29]:
vendor_sales_summ.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'Description', 'PurchasePrice',
       'ActualPrice', 'Volume', 'TotalPurchaseQuantity',
       'TotalPurchaseDollars', 'TotalSalesQuantity', 'TotalSalesDollars',
       'TotalSalesPrice', 'TotalExciseTax', 'FreightCost', 'Profit',
       'ProfitMargin', 'StockTurnover', 'S2PRatio'],
      dtype='object')

In [30]:
cursor=con.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS Vendor_Sales_Summary(
VendorNumber INT, VendorName VARCHAR(150), Brand INT, Description VARCHAR(150), PurchasePrice DECIMAL(10,2),
ActualPrice DECIMAL(10,2), Volume, TotalPurchaseQuantity INT, TotalPurchaseDollars DECIMAL(12,2),
TotalSalesQuantity DECIMAL(12,2), TotalSalesDollars DECIMAL(12,2), TotalSalesPrice DECIMAL(12,2), 
TotalExciseTax DECIMAL(12,2), FreightCost DECIMAL(12,2), Profit DECIMAL(12,2), ProfitMargin DECIMAL(12,2),
StockTurnover DECIMAL(12,2), S2PRatio DECIMAL(12,2), Primary Key (VendorNumber,Brand)
);""")

In [31]:
vendor_sales_summ.to_sql("Vendor_Sales_Summary",con,if_exists='replace',index=False)
pd.read_sql_query("select * from Vendor_Sales_Summary",con)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost,Profit,ProfitMargin,StockTurnover,S2PRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5101919.51,672819.31,260999.20,68601.68,1290667.91,25.297693,0.979108,1.338647
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4819073.49,561512.37,294438.66,144929.24,1015032.27,21.062810,0.976890,1.266830
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4538120.60,461140.15,343854.07,123780.22,1119816.92,24.675786,0.998575,1.327594
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4475972.88,420050.01,368242.80,257032.07,1214774.94,27.139908,0.993703,1.372493
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4223107.62,545778.28,249587.83,257032.07,1199901.61,28.412764,0.983556,1.396897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,15.95,10.96,0.55,27100.41,13.31,83.448276,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,65.66,1.47,7.04,50293.62,63.32,96.436186,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.98,0.99,0.10,14069.87,0.50,25.252525,1.000000,1.337838
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,143.28,77.61,15.12,257032.07,141.81,98.974037,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,85.14,33.66,4.46,38994.78,84.43,99.166079,86.000000,119.915493